import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/db/prisma";
import { decrypt } from "@/lib/hash";

export async function GET(req: NextRequest) {
  const session = await getServerSession(authOptions);
  if (!session?.user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const format = req.nextUrl.searchParams.get("format") || "json";
  const userId = (session.user as any).id;

  const connectedPlatforms = await prisma.connectedPlatform.findMany({
    where: { userId, status: "ACTIVE" },
    select: { id: true, platform: true },
  });
  const platformIds = connectedPlatforms.map((p) => p.id);

  const comments = await prisma.comment.findMany({
    where: { connectedPlatformId: { in: platformIds }, isRetained: true },
    orderBy: { ingestedAt: "desc" },
    select: {
      platform: true,
      videoId: true,
      authorDisplayNameEnc: true,
      commentTextRaw: true,
      commentTextNormalized: true,
      toxicScore: true,
      riskLabel: true,
      matchedPhrases: true,
      confidence: true,
      languageDetected: true,
      createdAt: true,
      authorHandleHash: true,
    },
  });

  const items = comments.map((c) => {
    let displayName = "[Anonymous]";
    try {
      if (c.authorDisplayNameEnc) displayName = decrypt(c.authorDisplayNameEnc);
    } catch {}
    const phrases: string[] = (() => { try { return JSON.parse(c.matchedPhrases || "[]"); } catch { return []; } })();
    return {
      platform: c.platform,
      videoId: c.videoId,
      authorName: displayName,
      commentText: c.commentTextRaw || c.commentTextNormalized || "[Purged]",
      toxicScore: c.toxicScore,
      riskLabel: c.riskLabel,
      matchedPhrases: phrases,
      confidence: c.confidence,
      language: c.languageDetected || "",
      date: c.createdAt.toISOString(),
    };
  });

  if (format === "csv") {
    const header = "platform,videoId,authorName,commentText,toxicScore,riskLabel,matchedPhrases,confidence,language,date\n";
    const rows = items
      .map((r) =>
        [
          r.platform,
          r.videoId,
          escapeCsv(r.authorName),
          escapeCsv(r.commentText),
          r.toxicScore,
          r.riskLabel,
          r.matchedPhrases.join(";"),
          r.confidence,
          r.language,
          r.date,
        ].join(",")
      )
      .join("\n");
    return new NextResponse(header + rows, {
      headers: {
        "Content-Type": "text/csv",
        "Content-Disposition": "attachment; filename=creator-safety-export.csv",
      },
    });
  }

  if (format === "report") {
    const flagged = items.filter((r) => r.riskLabel !== "low");
    const total = items.length;
    const allWords = [...new Set(items.flatMap((r) => r.matchedPhrases))];
    const lines = [
      "CREATOR SAFETY STUDIO - EXPORT REPORT",
      "=====================================",
      `Generated: ${new Date().toLocaleString()}`,
      `Total Comments Analyzed: ${total}`,
      `Flagged Comments: ${flagged.length} (${total > 0 ? Math.round((flagged.length / total) * 100) : 0}%)`,
      `Toxic Words Found: ${allWords.join(", ") || "none"}`,
      "",
      "--- FLAGGED COMMENTS ---",
      "",
      ...flagged.map((r, i) => [
        `#${i + 1}`,
        `  Platform: ${r.platform}`,
        `  Video: ${r.videoId}`,
        `  Author: ${r.authorName}`,
        `  Risk: ${r.riskLabel.toUpperCase()} (Score: ${Math.round(r.toxicScore * 100)}%)`,
        `  Toxic Words: ${r.matchedPhrases.join(", ") || "N/A"}`,
        `  Language: ${r.language || "unknown"}`,
        `  Date: ${new Date(r.date).toLocaleString()}`,
        `  Comment: "${r.commentText}"`,
        "",
      ].join("\n")),
      "=====================================",
      "Report generated by Creator Safety Studio",
    ];
    return new NextResponse(lines.join("\n"), {
      headers: {
        "Content-Type": "text/plain",
        "Content-Disposition": "attachment; filename=creator-safety-report.txt",
      },
    });
  }

  return NextResponse.json({ items, exportedAt: new Date().toISOString() });
}

function escapeCsv(val: string): string {
  if (val.includes(",") || val.includes('"') || val.includes("\n")) {
    return `"${val.replace(/"/g, '""')}"`;
  }
  return val;
}
